[package]
name = "veridag-merkle"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
veridag-crypto = { path = "../crypto" }
veridag-protocol-types = { path = "../protocol-types" }
thiserror.workspace = true

[lints]
workspace = true
