[package]
name = "veridag-net"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
veridag-codec = { version = "1.0.0", path = "../codec" }
veridag-crypto = { version = "1.0.0", path = "../crypto" }
veridag-dag = { version = "1.0.0", path = "../dag" }
veridag-protocol-types = { version = "1.0.0", path = "../protocol-types" }
thiserror.workspace = true
tokio.workspace = true
quinn.workspace = true
rcgen.workspace = true
rustls.workspace = true
futures.workspace = true
tracing.workspace = true
async-trait.workspace = true
libp2p = { version = "0.57", optional = true, default-features = false, features = ["tokio", "floodsub", "tcp", "noise", "yamux", "macros"] }

[features]
default = []
libp2p = ["dep:libp2p"]

[dev-dependencies]
veridag-checkpoint = { path = "../checkpoint" }
veridag-consensus = { path = "../consensus" }
veridag-execution = { path = "../execution" }
veridag-object-state = { path = "../object-state" }
veridag-transaction = { path = "../transaction" }
hex.workspace = true

[lints]
workspace = true
