[package]
name = "veridag-transaction"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
veridag-capabilities = { version = "1.0.0", path = "../capabilities" }
veridag-codec = { version = "1.0.0", path = "../codec" }
veridag-crypto = { version = "1.0.0", path = "../crypto" }
veridag-protocol-types = { version = "1.0.0", path = "../protocol-types" }
thiserror.workspace = true

[lints]
workspace = true
